"""add order history table, strategy table add more column for calculating position size

Revision ID: 054b36e0c039
Revises: 538e1477a546
Create Date: 2024-01-09 20:27:08.786561

"""
from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '054b36e0c039'
down_revision: Union[str, None] = '538e1477a546'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('order_history',
                    sa.Column('order_id', sa.String(length=100), nullable=True),
                    sa.Column('strategy_id', sa.String(length=50), nullable=True),
                    sa.Column('execution_time', sa.DateTime(), nullable=True),
                    sa.Column('symbol', sa.String(length=50), nullable=True),
                    sa.Column('action', sa.String(length=50), nullable=True),
                    sa.Column('price', sa.Float(), nullable=True),
                    sa.Column('amount', sa.Float(), nullable=True),
                    sa.Column('active', sa.Boolean(), nullable=True),
                    sa.Column('fund', sa.Float(), nullable=True),
                    sa.Column('exchange', sa.String(length=50), nullable=True),
                    sa.Column('order_payload', sa.String(), nullable=True),
                    sa.Column('id', mysql.INTEGER(unsigned=True), autoincrement=True, nullable=False),
                    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
                    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
                    sa.PrimaryKeyConstraint('id')
                    )
    op.add_column('strategy', sa.Column('symbol', sa.String(length=50), nullable=True))
    op.add_column('strategy', sa.Column('active_order', sa.Boolean(), nullable=True))
    op.add_column('strategy', sa.Column('fund', sa.Float(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('strategy', 'fund')
    op.drop_column('strategy', 'active_order')
    op.drop_column('strategy', 'symbol')
    op.drop_table('order_history')
    # ### end Alembic commands ###
