"""different fund in exchange

Revision ID: 091396cfea0e
Revises: 9aa427a66ff2
Create Date: 2024-02-15 13:22:30.859322

"""
from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = '091396cfea0e'
down_revision: Union[str, None] = '9aa427a66ff2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('strategy_management', sa.Column('exchange', sa.String(length=50), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('strategy_management', 'exchange')
    # ### end Alembic commands ###
