"""leverage flag

Revision ID: 0dcb45fec475
Revises: 46a3a2cf3fe2
Create Date: 2024-03-10 13:00:46.480788

"""
from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = '0dcb45fec475'
down_revision: Union[str, None] = '46a3a2cf3fe2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('strategy', sa.Column('is_lev', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('strategy', 'is_lev')
    # ### end Alembic commands ###
