"""remove unwanted column

Revision ID: 1b3bab42ed85
Revises: 74e22783b20e
Create Date: 2024-10-25 23:30:48.801341

"""
from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = '1b3bab42ed85'
down_revision: Union[str, None] = '74e22783b20e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('strategy', 'parameter_4')
    op.drop_column('strategy', 'value_2')
    op.drop_column('strategy', 'parameter_1')
    op.drop_column('strategy', 'lev_mdd')
    op.drop_column('strategy', 'lev_add')
    op.drop_column('strategy', 'value_1')
    op.drop_column('strategy', 'wfe')
    op.drop_column('strategy', 'lev_ret')
    op.drop_column('strategy', 'parameter_2')
    op.drop_column('strategy', 'value_4')
    op.drop_column('strategy', 'sim_add')
    op.drop_column('strategy', 'parameter_3')
    op.drop_column('strategy', 'l_sr')
    op.drop_column('strategy', 'value_5')
    op.drop_column('strategy', 'bnh_add')
    op.drop_column('strategy', 'value_3')
    op.drop_column('strategy', 'parameter_5')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('strategy', sa.Column('parameter_5', sa.VARCHAR(length=50), autoincrement=False, nullable=True))
    op.add_column('strategy', sa.Column('value_3', sa.VARCHAR(length=50), autoincrement=False, nullable=True))
    op.add_column('strategy',
                  sa.Column('bnh_add', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True))
    op.add_column('strategy', sa.Column('value_5', sa.VARCHAR(length=50), autoincrement=False, nullable=True))
    op.add_column('strategy', sa.Column('l_sr', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True))
    op.add_column('strategy', sa.Column('parameter_3', sa.VARCHAR(length=50), autoincrement=False, nullable=True))
    op.add_column('strategy',
                  sa.Column('sim_add', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True))
    op.add_column('strategy', sa.Column('value_4', sa.VARCHAR(length=50), autoincrement=False, nullable=True))
    op.add_column('strategy', sa.Column('parameter_2', sa.VARCHAR(length=50), autoincrement=False, nullable=True))
    op.add_column('strategy',
                  sa.Column('lev_ret', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True))
    op.add_column('strategy', sa.Column('wfe', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True))
    op.add_column('strategy', sa.Column('value_1', sa.VARCHAR(length=50), autoincrement=False, nullable=True))
    op.add_column('strategy',
                  sa.Column('lev_add', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True))
    op.add_column('strategy',
                  sa.Column('lev_mdd', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True))
    op.add_column('strategy', sa.Column('parameter_1', sa.VARCHAR(length=50), autoincrement=False, nullable=True))
    op.add_column('strategy', sa.Column('value_2', sa.VARCHAR(length=50), autoincrement=False, nullable=True))
    op.add_column('strategy', sa.Column('parameter_4', sa.VARCHAR(length=50), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
