"""seperate active_order and fund to new table

Revision ID: 2bd8031c5d6e
Revises: fc781d2604f2
Create Date: 2024-01-30 17:47:02.985986

"""
from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '2bd8031c5d6e'
down_revision: Union[str, None] = 'fc781d2604f2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('strategy_management',
                    sa.Column('strategy_id', sa.String(length=50), nullable=True),
                    sa.Column('active_order', sa.Boolean(), nullable=True),
                    sa.Column('fund', sa.Float(), nullable=True),
                    sa.Column('id', mysql.INTEGER(unsigned=True), autoincrement=True, nullable=False),
                    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
                    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
                    sa.ForeignKeyConstraint(['strategy_id'], ['strategy.strategy_id'], ),
                    sa.PrimaryKeyConstraint('id'),
                    sa.UniqueConstraint('strategy_id')
                    )
    op.drop_column('strategy', 'active_order')
    op.drop_column('strategy', 'fund')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('strategy', sa.Column('fund', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True))
    op.add_column('strategy', sa.Column('active_order', sa.BOOLEAN(), autoincrement=False, nullable=True))
    op.drop_table('strategy_management')
    # ### end Alembic commands ###
