"""order history capture order created/closed time

Revision ID: 2fa7c9f57df8
Revises: 9ee537214cb6
Create Date: 2024-01-10 21:10:10.394043

"""
from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = '2fa7c9f57df8'
down_revision: Union[str, None] = '9ee537214cb6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('order_history', sa.Column('open_timestamp', sa.String(length=20), nullable=True))
    op.add_column('order_history', sa.Column('open_datetime', sa.DateTime(), nullable=True))
    op.add_column('order_history', sa.Column('fill_timestamp', sa.String(length=20), nullable=True))
    op.add_column('order_history', sa.Column('fill_datetime', sa.DateTime(), nullable=True))
    op.alter_column('order_history', 'order_price',
                    existing_type=sa.REAL(),
                    type_=sa.Float(precision=20),
                    existing_nullable=True)
    op.alter_column('order_history', 'avg_price',
                    existing_type=sa.REAL(),
                    type_=sa.Float(precision=20),
                    existing_nullable=True)
    op.alter_column('order_history', 'exec_value',
                    existing_type=sa.REAL(),
                    type_=sa.Float(precision=20),
                    existing_nullable=True)
    op.alter_column('order_history', 'order_amt',
                    existing_type=sa.REAL(),
                    type_=sa.Float(precision=20),
                    existing_nullable=True)
    op.alter_column('order_history', 'filled_amt',
                    existing_type=sa.REAL(),
                    type_=sa.Float(precision=20),
                    existing_nullable=True)
    op.alter_column('order_history', 'fee_rate',
                    existing_type=sa.REAL(),
                    type_=sa.Float(precision=20),
                    existing_nullable=True)
    op.alter_column('order_history', 'total_fee',
                    existing_type=sa.REAL(),
                    type_=sa.Float(precision=20),
                    existing_nullable=True)
    op.alter_column('order_history', 'position_size',
                    existing_type=sa.REAL(),
                    type_=sa.Float(precision=10),
                    existing_nullable=True)
    op.alter_column('order_history', 'fund_diff',
                    existing_type=sa.REAL(),
                    type_=sa.Float(precision=20),
                    existing_nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('order_history', 'fund_diff',
                    existing_type=sa.Float(precision=20),
                    type_=sa.REAL(),
                    existing_nullable=True)
    op.alter_column('order_history', 'position_size',
                    existing_type=sa.Float(precision=10),
                    type_=sa.REAL(),
                    existing_nullable=True)
    op.alter_column('order_history', 'total_fee',
                    existing_type=sa.Float(precision=20),
                    type_=sa.REAL(),
                    existing_nullable=True)
    op.alter_column('order_history', 'fee_rate',
                    existing_type=sa.Float(precision=20),
                    type_=sa.REAL(),
                    existing_nullable=True)
    op.alter_column('order_history', 'filled_amt',
                    existing_type=sa.Float(precision=20),
                    type_=sa.REAL(),
                    existing_nullable=True)
    op.alter_column('order_history', 'order_amt',
                    existing_type=sa.Float(precision=20),
                    type_=sa.REAL(),
                    existing_nullable=True)
    op.alter_column('order_history', 'exec_value',
                    existing_type=sa.Float(precision=20),
                    type_=sa.REAL(),
                    existing_nullable=True)
    op.alter_column('order_history', 'avg_price',
                    existing_type=sa.Float(precision=20),
                    type_=sa.REAL(),
                    existing_nullable=True)
    op.alter_column('order_history', 'order_price',
                    existing_type=sa.Float(precision=20),
                    type_=sa.REAL(),
                    existing_nullable=True)
    op.drop_column('order_history', 'fill_datetime')
    op.drop_column('order_history', 'fill_timestamp')
    op.drop_column('order_history', 'open_datetime')
    op.drop_column('order_history', 'open_timestamp')
    # ### end Alembic commands ###
