"""unique for strategy id, add strategy name

Revision ID: 3496f590d681
Revises: 31197b73b7ba
Create Date: 2024-01-11 12:08:36.052395

"""
from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = '3496f590d681'
down_revision: Union[str, None] = '31197b73b7ba'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(None, 'order_history', ['order_id'])
    op.add_column('strategy', sa.Column('strategy_name', sa.String(length=50), nullable=True))
    op.create_unique_constraint(None, 'strategy', ['strategy_id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'strategy', type_='unique')
    op.drop_column('strategy', 'strategy_name')
    op.drop_constraint(None, 'order_history', type_='unique')
    # ### end Alembic commands ###
