"""add position size

Revision ID: 35f4ce8a2955
Revises: 1b3bab42ed85
Create Date: 2024-11-19 12:36:20.224260

"""
from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = '35f4ce8a2955'
down_revision: Union[str, None] = '1b3bab42ed85'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('alert_history', sa.Column('position_size', sa.String(length=50), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('alert_history', 'position_size')
    # ### end Alembic commands ###
