"""need strat_mgmt_id to manage

Revision ID: 3b7599147c69
Revises: 091396cfea0e
Create Date: 2024-02-15 13:37:42.960297

"""
from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = '3b7599147c69'
down_revision: Union[str, None] = '091396cfea0e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('strategy_management', sa.Column('strat_mgmt_id', sa.String(length=100), nullable=True))
    op.drop_constraint('strategy_management_strategy_id_key', 'strategy_management', type_='unique')
    op.create_unique_constraint(None, 'strategy_management', ['strat_mgmt_id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'strategy_management', type_='unique')
    op.create_unique_constraint('strategy_management_strategy_id_key', 'strategy_management', ['strategy_id'])
    op.drop_column('strategy_management', 'strat_mgmt_id')
    # ### end Alembic commands ###
