"""add strategy direction

Revision ID: 413b9c0a6f4d
Revises: bbb49a462680
Create Date: 2024-01-26 00:30:35.725849

"""
from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = '413b9c0a6f4d'
down_revision: Union[str, None] = 'bbb49a462680'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('strategy', sa.Column('direction', sa.String(length=10), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('strategy', 'direction')
    # ### end Alembic commands ###
