"""remove foreign key

Revision ID: 419b724e86e4
Revises: c25c876d7fef
Create Date: 2024-01-31 09:36:46.338825

"""
from typing import Sequence, Union

from alembic import op

# revision identifiers, used by Alembic.
revision: str = '419b724e86e4'
down_revision: Union[str, None] = 'c25c876d7fef'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('strategy_strategy_id_fkey', 'strategy', type_='foreignkey')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_foreign_key('strategy_strategy_id_fkey', 'strategy', 'strategy_management', ['strategy_id'],
                          ['strategy_id'])
    # ### end Alembic commands ###
