"""add exchange column in alert_history table 2

Revision ID: 538e1477a546
Revises: c376c1a97477
Create Date: 2024-01-09 16:44:33.784537

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '538e1477a546'
down_revision: Union[str, None] = 'c376c1a97477'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('alert_history', sa.Column('symbol', sa.String(length=50), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('alert_history', 'symbol')
    # ### end Alembic commands ###
