"""add add column

Revision ID: 74e22783b20e
Revises: 0dcb45fec475
Create Date: 2024-03-20 21:12:46.672170

"""
from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = '74e22783b20e'
down_revision: Union[str, None] = '0dcb45fec475'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('strategy', sa.Column('sim_add', sa.Float(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('strategy', 'sim_add')
    # ### end Alembic commands ###
