"""add calculation for position sizing

Revision ID: 7c4b55f0029b
Revises: 054b36e0c039
Create Date: 2024-01-10 01:20:34.564847

"""
from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = '7c4b55f0029b'
down_revision: Union[str, None] = '054b36e0c039'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('order_history', sa.Column('position_size', sa.Float(precision=10), nullable=True))
    op.add_column('order_history', sa.Column('position_fund', sa.Float(), nullable=True))
    op.add_column('order_history', sa.Column('total_fund', sa.Float(), nullable=True))
    op.drop_column('order_history', 'fund')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('order_history',
                  sa.Column('fund', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True))
    op.drop_column('order_history', 'total_fund')
    op.drop_column('order_history', 'position_fund')
    op.drop_column('order_history', 'position_size')
    # ### end Alembic commands ###
