"""active strategy

Revision ID: 80dd0105b847
Revises: 413b9c0a6f4d
Create Date: 2024-01-27 08:46:32.677396

"""
from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = '80dd0105b847'
down_revision: Union[str, None] = '413b9c0a6f4d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('strategy', sa.Column('active', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('strategy', 'active')
    # ### end Alembic commands ###
