"""init fund for strate mgmt

Revision ID: 8a276cb31812
Revises: 75ec4e1703ec
Create Date: 2024-03-07 01:02:47.600541

"""
from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = '8a276cb31812'
down_revision: Union[str, None] = '75ec4e1703ec'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('strategy_management', sa.Column('init_fund', sa.Float(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('strategy_management', 'init_fund')
    # ### end Alembic commands ###
