"""error table

Revision ID: 9aa427a66ff2
Revises: 14741bc7a704
Create Date: 2024-02-13 00:36:02.195034

"""
from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '9aa427a66ff2'
down_revision: Union[str, None] = '14741bc7a704'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('order_execution_error',
                    sa.Column('alert_id', mysql.INTEGER(display_width=10), nullable=True),
                    sa.Column('error', sa.String(), nullable=True),
                    sa.Column('error_stack', sa.String(), nullable=True),
                    sa.Column('id', mysql.INTEGER(unsigned=True), autoincrement=True, nullable=False),
                    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
                    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
                    sa.PrimaryKeyConstraint('id')
                    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('order_execution_error')
    # ### end Alembic commands ###
