"""add more column needed for tracking order

Revision ID: 9ee537214cb6
Revises: 7c4b55f0029b
Create Date: 2024-01-10 18:23:16.500587

"""
from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '9ee537214cb6'
down_revision: Union[str, None] = '7c4b55f0029b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('order_history', sa.Column('exec_time', sa.DateTime(), nullable=True))
    op.add_column('order_history', sa.Column('source_symbol', sa.String(length=10), nullable=True))
    op.add_column('order_history', sa.Column('exchange_symbol', sa.String(length=10), nullable=True))
    op.add_column('order_history', sa.Column('order_status', sa.String(length=10), nullable=True))
    op.add_column('order_history', sa.Column('order_price', sa.Float(precision=20), nullable=True))
    op.add_column('order_history', sa.Column('avg_price', sa.Float(precision=20), nullable=True))
    op.add_column('order_history', sa.Column('exec_value', sa.Float(precision=20), nullable=True))
    op.add_column('order_history', sa.Column('order_amt', sa.Float(precision=20), nullable=True))
    op.add_column('order_history', sa.Column('filled_amt', sa.Float(precision=20), nullable=True))
    op.add_column('order_history', sa.Column('fee_rate', sa.Float(precision=20), nullable=True))
    op.add_column('order_history', sa.Column('total_fee', sa.Float(precision=20), nullable=True))
    op.add_column('order_history', sa.Column('fund_diff', sa.Float(precision=20), nullable=True))
    op.add_column('order_history', sa.Column('order_payload_1', sa.String(), nullable=True))
    op.add_column('order_history', sa.Column('order_payload_2', sa.String(), nullable=True))
    op.alter_column('order_history', 'action',
                    existing_type=sa.VARCHAR(length=50),
                    type_=sa.String(length=10),
                    existing_nullable=True)
    op.alter_column('order_history', 'position_size',
                    existing_type=sa.REAL(),
                    type_=sa.Float(precision=10),
                    existing_nullable=True)
    op.alter_column('order_history', 'exchange',
                    existing_type=sa.VARCHAR(length=50),
                    type_=sa.String(length=20),
                    existing_nullable=True)
    op.drop_column('order_history', 'price')
    op.drop_column('order_history', 'execution_time')
    op.drop_column('order_history', 'symbol')
    op.drop_column('order_history', 'order_payload')
    op.drop_column('order_history', 'amount')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('order_history',
                  sa.Column('amount', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True))
    op.add_column('order_history', sa.Column('order_payload', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('order_history', sa.Column('symbol', sa.VARCHAR(length=50), autoincrement=False, nullable=True))
    op.add_column('order_history',
                  sa.Column('execution_time', postgresql.TIMESTAMP(), autoincrement=False, nullable=True))
    op.add_column('order_history',
                  sa.Column('price', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True))
    op.alter_column('order_history', 'exchange',
                    existing_type=sa.String(length=20),
                    type_=sa.VARCHAR(length=50),
                    existing_nullable=True)
    op.alter_column('order_history', 'position_size',
                    existing_type=sa.Float(precision=10),
                    type_=sa.REAL(),
                    existing_nullable=True)
    op.alter_column('order_history', 'action',
                    existing_type=sa.String(length=10),
                    type_=sa.VARCHAR(length=50),
                    existing_nullable=True)
    op.drop_column('order_history', 'order_payload_2')
    op.drop_column('order_history', 'order_payload_1')
    op.drop_column('order_history', 'fund_diff')
    op.drop_column('order_history', 'total_fee')
    op.drop_column('order_history', 'fee_rate')
    op.drop_column('order_history', 'filled_amt')
    op.drop_column('order_history', 'order_amt')
    op.drop_column('order_history', 'exec_value')
    op.drop_column('order_history', 'avg_price')
    op.drop_column('order_history', 'order_price')
    op.drop_column('order_history', 'order_status')
    op.drop_column('order_history', 'exchange_symbol')
    op.drop_column('order_history', 'source_symbol')
    op.drop_column('order_history', 'exec_time')
    # ### end Alembic commands ###
