"""swap foreign key

Revision ID: c25c876d7fef
Revises: 2bd8031c5d6e
Create Date: 2024-01-31 04:02:50.990311

"""
from typing import Sequence, Union

from alembic import op

# revision identifiers, used by Alembic.
revision: str = 'c25c876d7fef'
down_revision: Union[str, None] = '2bd8031c5d6e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_foreign_key(None, 'strategy', 'strategy_management', ['strategy_id'], ['strategy_id'])
    op.drop_constraint('strategy_management_strategy_id_fkey', 'strategy_management', type_='foreignkey')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_foreign_key('strategy_management_strategy_id_fkey', 'strategy_management', 'strategy', ['strategy_id'],
                          ['strategy_id'])
    op.drop_constraint(None, 'strategy', type_='foreignkey')
    # ### end Alembic commands ###
